FROM node:14

WORKDIR /app

COPY . /app

RUN npm install

# Install AWS CLI
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    awscli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set AWS credentials as environment variables
ENV AWS_ACCESS_KEY_ID=_YOUR_KEY   #your key mention here
ENV AWS_SECRET_ACCESS_KEY=_YOUR_PASS   #your pass mention here

# Mount S3 bucket
RUN aws s3 sync s3://manjeetyadavrajokri /app/s3

EXPOSE 8081

CMD ["node", "server.js"]

